import { QA_PROMPT, SOFTWARE_ENGINEER_PROMPT, TWEETER_PROMPT } from '@/templates/prompts';

export const prompts = {
  ASSISTANT: QA_PROMPT,
  SOFTWARE_ENGINEER: SOFTWARE_ENGINEER_PROMPT,
  TWEETER: TWEETER_PROMPT,
};
